rootProject.name = "rayvion"

include("commons")
include("system")
include("system-manager")
include("entity")
include("entity-impl")
include("event")
include("event-impl")
include("scheduler")
include("scheduler-impl")
include("tick")
include("tick-impl")
include("world")
include("world-impl")
include("transform")
include("transform-impl")
include("physics")
include("physics-impl")
include("graphics")
include("graphics-impl")
include("quest")
include("quest-impl")
include("game")